#!/usr/bin/env python3
"""
ctxbench validate — CI entry point. Validates a submitted results/ folder
against the schema, then renders LEADERBOARD.md.

Usage:
  python validate.py results/            # validate only, exit 1 on failure
  python validate.py results/ --render   # also emit LEADERBOARD.md
"""
import argparse, json, os, re, sys

MIN_BUILD = 10330
REQUIRED_DEPTHS = {0, 4096, 16384, 32768, 65536}
REQUIRED_MANIFEST = ["machine", "hardware", "engine", "method"]
REQUIRED_HW = ["gpu", "vram_mib", "cpu"]
REQUIRED_ENGINE = ["name", "build_number"]

errors = []

def fail(msg):
    errors.append(msg)
    print(f"  FAIL: {msg}")

def check_manifest(path):
    try:
        with open(path) as f:
            m = json.load(f)
    except Exception as e:
        fail(f"{path}: unparseable manifest: {e}")
        return None
    for k in REQUIRED_MANIFEST:
        if k not in m:
            fail(f"{path}: missing top-level '{k}'")
    for k in REQUIRED_HW:
        if k not in m.get("hardware", {}):
            fail(f"{path}: hardware missing '{k}'")
    for k in REQUIRED_ENGINE:
        if k not in m.get("engine", {}):
            fail(f"{path}: engine missing '{k}'")
    if m.get("engine", {}).get("build_number", 0) < MIN_BUILD:
        fail(f"{path}: build_number {m['engine'].get('build_number')} < {MIN_BUILD} (stale build = garbage curves)")
    depths = m.get("method", {}).get("depths", [])
    if set(depths) != REQUIRED_DEPTHS:
        fail(f"{path}: depths {depths} != required {sorted(REQUIRED_DEPTHS)}")
    return m

def check_run(path, manifest):
    try:
        with open(path) as f:
            r = json.load(f)
    except Exception as e:
        fail(f"{path}: unparseable: {e}")
        return
    for k in ["model_key", "model_name", "quant", "tests"]:
        if k not in r:
            fail(f"{path}: missing '{k}'")
    tests = r.get("tests", [])
    if not tests:
        fail(f"{path}: no tests")
    depths = set()
    for t in tests:
        for k in ["depth", "n_prompt", "n_gen", "avg_ts", "stddev_ts"]:
            if k not in t:
                fail(f"{path}: test missing '{k}'")
        if t.get("avg_ts", 0) <= 0:
            fail(f"{path}: avg_ts <= 0")
        if t.get("stddev_ts", -1) < 0:
            fail(f"{path}: stddev_ts < 0")
        depths.add(t.get("depth"))
    if manifest and set(depths) != REQUIRED_DEPTHS:
        fail(f"{path}: depths {sorted(depths)} != required {sorted(REQUIRED_DEPTHS)}")

def render_leaderboard(root):
    """Render LEADERBOARD.md from validated submissions."""
    lines = ["# LEADERBOARD — decode t/s at depth (Q4_K_M, llama.cpp b10330+)",
             "_Auto-generated by `validate.py --render`. Do not edit by hand._",
             "Depth sweep uses pg 2048,128. Headline numbers (pg 128,32) are the d0 rows.",
             "", "| Machine | GPU | CPU | Model | Quant | Depth | tg t/s | pp t/s |",
             "|---|---|---|---|---|---|---|---|"]
    machines = sorted(d for d in os.listdir(root) if os.path.isdir(os.path.join(root, d)))
    for mach in machines:
        mpath = os.path.join(root, mach, "manifest.json")
        if not os.path.exists(mpath):
            continue
        with open(mpath) as f:
            m = json.load(f)
        hw = m.get("hardware", {})
        runs_dir = os.path.join(root, mach, "runs")
        if not os.path.isdir(runs_dir):
            continue
        for fn in sorted(os.listdir(runs_dir)):
            if not fn.endswith(".json"):
                continue
            with open(os.path.join(runs_dir, fn)) as f:
                r = json.load(f)
            # one row per depth: tg from the depth-sweep test (2048,128),
            # pp from the pp-only test (512,0); fall back to any valid test
            per_depth = {}
            for t in r.get("tests", []):
                d = t.get("depth", 0)
                entry = per_depth.setdefault(d, {"tg": None, "pp": None})
                if t.get("n_prompt", 0) > 0 and t.get("n_gen", 0) > 0:
                    if t.get("n_prompt") == 2048 or entry["tg"] is None:
                        entry["tg"] = t["avg_ts"]
                elif t.get("n_prompt", 0) > 0 and t.get("n_gen", 0) == 0:
                    entry["pp"] = t["avg_ts"]
            for d in sorted(per_depth):
                e = per_depth[d]
                if e["tg"] is None:
                    continue
                lines.append(
                    f"| {mach} | {hw.get('gpu','?')} | {hw.get('cpu','?')[:30]} "
                    f"| {r.get('model_name','?')} | {r.get('quant','?')} "
                    f"| {d} | {e['tg']:.1f} | {e['pp']:.1f} |")
    with open(os.path.join(os.path.dirname(root) or ".", "LEADERBOARD.md"), "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  Rendered LEADERBOARD.md ({len(lines)-3} rows)")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("results", help="results/ directory")
    ap.add_argument("--render", action="store_true")
    args = ap.parse_args()

    root = args.results.rstrip("/\\")
    if not os.path.isdir(root):
        print(f"Not a directory: {root}", file=sys.stderr)
        sys.exit(1)

    machines = [d for d in os.listdir(root) if os.path.isdir(os.path.join(root, d))]
    if not machines:
        print("No machine subdirectories found.", file=sys.stderr)
        sys.exit(1)

    for mach in machines:
        mdir = os.path.join(root, mach)
        print(f"=== {mach} ===")
        manifest = check_manifest(os.path.join(mdir, "manifest.json"))
        runs = [f for f in os.listdir(os.path.join(mdir, "runs")) if f.endswith(".json")] \
               if os.path.isdir(os.path.join(mdir, "runs")) else []
        if not runs:
            fail(f"{mach}: no run files in runs/")
        for fn in runs:
            check_run(os.path.join(mdir, "runs", fn), manifest)

    if errors:
        print(f"\n{len(errors)} error(s) — submission rejected.")
        sys.exit(1)
    print("\nAll checks passed.")
    if args.render:
        render_leaderboard(root)

if __name__ == "__main__":
    main()
